import turtle
t = turtle.Turtle()
s = turtle.Screen()
s.bgcolor('dark grey')
t.color('white')
t.speed(5)
t.goto(-250,0)
t.forward(500)
t.left(90)
t.forward(200)
t.left(90)
t.forward(500)
t.left(90)
t.forward(200)
t.color('white')
t.penup()
t.goto(0,90)
t.write("TERIMA KASIH TELAH MENGGUNAKAN ", align='center', font='Times 18 normal')
t.color('white')
t.hideturtle()
turtle.done()